import {
  GradeAssessmentApprovalStatus,
  GradeAssessmentDeliveryMode,
  GradeAssessmentType,
  GradeScopeType,
  Prisma,
} from '@prisma/client';
import { presentGradeAssessment } from '../presenters/grade-assessment.presenter';

describe('grade assessment presenter', () => {
  it('maps statuses, scope, delivery mode, and decimals to frontend fields', () => {
    const presented = presentGradeAssessment({
      id: 'assessment-1',
      schoolId: 'school-1',
      academicYearId: 'year-1',
      termId: 'term-1',
      subjectId: 'subject-1',
      scopeType: GradeScopeType.CLASSROOM,
      scopeKey: 'classroom-1',
      stageId: 'stage-1',
      gradeId: 'grade-1',
      sectionId: 'section-1',
      classroomId: 'classroom-1',
      titleEn: 'Quiz 1',
      titleAr: 'Quiz 1 AR',
      type: GradeAssessmentType.QUIZ,
      deliveryMode: GradeAssessmentDeliveryMode.SCORE_ONLY,
      date: new Date('2026-09-15T00:00:00.000Z'),
      weight: new Prisma.Decimal(12.5),
      maxScore: new Prisma.Decimal(25),
      expectedTimeMinutes: 30,
      approvalStatus: GradeAssessmentApprovalStatus.APPROVED,
      publishedAt: new Date('2026-09-16T08:00:00.000Z'),
      publishedById: 'user-1',
      approvedAt: new Date('2026-09-17T08:00:00.000Z'),
      approvedById: 'user-3',
      lockedAt: new Date('2026-09-20T08:00:00.000Z'),
      lockedById: 'user-2',
      createdById: 'user-1',
      createdAt: new Date('2026-09-15T08:00:00.000Z'),
      updatedAt: new Date('2026-09-16T08:00:00.000Z'),
      deletedAt: null,
      subject: {
        id: 'subject-1',
        nameAr: 'Math AR',
        nameEn: 'Math',
        code: 'MATH',
        color: '#2563eb',
        isActive: true,
      },
    });

    expect(presented).toEqual({
      id: 'assessment-1',
      academicYearId: 'year-1',
      yearId: 'year-1',
      termId: 'term-1',
      subjectId: 'subject-1',
      subject: {
        id: 'subject-1',
        name: 'Math',
        nameAr: 'Math AR',
        nameEn: 'Math',
        code: 'MATH',
        color: '#2563eb',
      },
      scopeType: 'classroom',
      scopeKey: 'classroom-1',
      scopeId: 'classroom-1',
      stageId: 'stage-1',
      gradeId: 'grade-1',
      sectionId: 'section-1',
      classroomId: 'classroom-1',
      title: 'Quiz 1',
      titleEn: 'Quiz 1',
      titleAr: 'Quiz 1 AR',
      type: 'QUIZ',
      deliveryMode: 'SCORE_ONLY',
      date: '2026-09-15',
      weight: 12.5,
      maxScore: 25,
      expectedTimeMinutes: 30,
      approvalStatus: 'approved',
      isLocked: true,
      publishedAt: '2026-09-16T08:00:00.000Z',
      publishedById: 'user-1',
      approvedAt: '2026-09-17T08:00:00.000Z',
      approvedById: 'user-3',
      lockedAt: '2026-09-20T08:00:00.000Z',
      lockedById: 'user-2',
      createdById: 'user-1',
      createdAt: '2026-09-15T08:00:00.000Z',
      updatedAt: '2026-09-16T08:00:00.000Z',
    });
  });
});
