import { Module } from '@nestjs/common';
import { HomeworkModule } from '../../homework/homework.module';
import { TeacherAppAccessService } from '../access/teacher-app-access.service';
import { TeacherAppAllocationReadAdapter } from '../access/teacher-app-allocation-read.adapter';
import { TeacherHomeworkOwnershipService } from './application/teacher-homework-ownership.service';
import {
  BulkReviewTeacherHomeworkSubmissionAnswersUseCase,
  CancelTeacherHomeworkAssignmentUseCase,
  CloseTeacherHomeworkAssignmentUseCase,
  CreateTeacherHomeworkAttachmentUseCase,
  CreateTeacherHomeworkAssignmentUseCase,
  CreateTeacherHomeworkQuestionOptionUseCase,
  CreateTeacherHomeworkQuestionUseCase,
  DeleteTeacherHomeworkAttachmentUseCase,
  DeleteTeacherHomeworkQuestionOptionUseCase,
  DeleteTeacherHomeworkQuestionUseCase,
  GetTeacherHomeworkAssignmentUseCase,
  GetTeacherHomeworkGradeSyncStatusUseCase,
  GetTeacherHomeworkQuestionUseCase,
  GetTeacherHomeworkSubmissionUseCase,
  GetTeacherHomeworksDashboardUseCase,
  ListTeacherHomeworkAttachmentsUseCase,
  ListTeacherHomeworkAssignmentsUseCase,
  ListTeacherHomeworkQuestionsUseCase,
  ListTeacherHomeworkSubmissionAnswersUseCase,
  ListTeacherHomeworkSubmissionAttachmentsUseCase,
  ListTeacherHomeworkSubmissionsUseCase,
  ListTeacherHomeworkTargetsUseCase,
  PublishTeacherHomeworkAssignmentUseCase,
  ReorderTeacherHomeworkAttachmentUseCase,
  ReorderTeacherHomeworkQuestionOptionUseCase,
  ReorderTeacherHomeworkQuestionUseCase,
  ReviewTeacherHomeworkSubmissionAnswerUseCase,
  ReviewTeacherHomeworkSubmissionUseCase,
  ResolveTeacherHomeworkTargetsUseCase,
  SyncTeacherHomeworkAssignmentToGradesUseCase,
  SyncTeacherHomeworkSubmissionToGradesUseCase,
  UpdateTeacherHomeworkAttachmentUseCase,
  UpdateTeacherHomeworkAssignmentUseCase,
  UpdateTeacherHomeworkQuestionOptionUseCase,
  UpdateTeacherHomeworkQuestionUseCase,
} from './application/teacher-homeworks.use-cases';
import { TeacherHomeworksController } from './controller/teacher-homeworks.controller';
import { TeacherHomeworksReadAdapter } from './infrastructure/teacher-homeworks-read.adapter';

@Module({
  imports: [HomeworkModule],
  controllers: [TeacherHomeworksController],
  providers: [
    TeacherAppAccessService,
    TeacherAppAllocationReadAdapter,
    TeacherHomeworksReadAdapter,
    TeacherHomeworkOwnershipService,
    GetTeacherHomeworksDashboardUseCase,
    ListTeacherHomeworkAssignmentsUseCase,
    CreateTeacherHomeworkAssignmentUseCase,
    GetTeacherHomeworkAssignmentUseCase,
    UpdateTeacherHomeworkAssignmentUseCase,
    PublishTeacherHomeworkAssignmentUseCase,
    CloseTeacherHomeworkAssignmentUseCase,
    CancelTeacherHomeworkAssignmentUseCase,
    ListTeacherHomeworkTargetsUseCase,
    ResolveTeacherHomeworkTargetsUseCase,
    ListTeacherHomeworkQuestionsUseCase,
    CreateTeacherHomeworkQuestionUseCase,
    GetTeacherHomeworkQuestionUseCase,
    UpdateTeacherHomeworkQuestionUseCase,
    ReorderTeacherHomeworkQuestionUseCase,
    DeleteTeacherHomeworkQuestionUseCase,
    CreateTeacherHomeworkQuestionOptionUseCase,
    UpdateTeacherHomeworkQuestionOptionUseCase,
    ReorderTeacherHomeworkQuestionOptionUseCase,
    DeleteTeacherHomeworkQuestionOptionUseCase,
    ListTeacherHomeworkAttachmentsUseCase,
    CreateTeacherHomeworkAttachmentUseCase,
    UpdateTeacherHomeworkAttachmentUseCase,
    ReorderTeacherHomeworkAttachmentUseCase,
    DeleteTeacherHomeworkAttachmentUseCase,
    ListTeacherHomeworkSubmissionsUseCase,
    GetTeacherHomeworkSubmissionUseCase,
    ListTeacherHomeworkSubmissionAnswersUseCase,
    ReviewTeacherHomeworkSubmissionAnswerUseCase,
    BulkReviewTeacherHomeworkSubmissionAnswersUseCase,
    ListTeacherHomeworkSubmissionAttachmentsUseCase,
    ReviewTeacherHomeworkSubmissionUseCase,
    GetTeacherHomeworkGradeSyncStatusUseCase,
    SyncTeacherHomeworkAssignmentToGradesUseCase,
    SyncTeacherHomeworkSubmissionToGradesUseCase,
  ],
})
export class TeacherHomeworksModule {}
