import { Module } from '@nestjs/common';
import { AuthModule } from '../iam/auth/auth.module';
import {
  CancelHomeworkAssignmentUseCase,
  CloseHomeworkAssignmentUseCase,
  CreateHomeworkAssignmentUseCase,
  GetHomeworkAssignmentUseCase,
  ListHomeworkAssignmentsUseCase,
  ListHomeworkTargetsUseCase,
  PublishHomeworkAssignmentUseCase,
  ResolveHomeworkTargetsUseCase,
  UpdateHomeworkAssignmentUseCase,
} from './application/homework-assignments.use-cases';
import {
  GetHomeworkSubmissionUseCase,
  GetHomeworkSubmissionForReviewUseCase,
  ListHomeworkSubmissionsForReviewUseCase,
  ReviewHomeworkSubmissionUseCase,
  SaveHomeworkSubmissionDraftUseCase,
  SubmitHomeworkSubmissionUseCase,
} from './application/homework-submissions.use-cases';
import {
  GetHomeworkSubmissionAnswerUseCase,
  ListHomeworkSubmissionAnswersUseCase,
  ListStudentHomeworkAnswersUseCase,
  SaveStudentHomeworkAnswerUseCase,
  SaveStudentHomeworkAnswersDraftUseCase,
} from './application/homework-answers.use-cases';
import {
  CreateStudentHomeworkSubmissionAttachmentUseCase,
  DeleteStudentHomeworkSubmissionAttachmentUseCase,
  ListHomeworkSubmissionAttachmentsUseCase,
  ListStudentHomeworkSubmissionAttachmentsUseCase,
  ReorderStudentHomeworkSubmissionAttachmentUseCase,
  UpdateStudentHomeworkSubmissionAttachmentUseCase,
} from './application/homework-submission-attachments.use-cases';
import {
  CreateHomeworkAttachmentUseCase,
  DeleteHomeworkAttachmentUseCase,
  ListHomeworkAttachmentsUseCase,
  ReorderHomeworkAttachmentUseCase,
  UpdateHomeworkAttachmentUseCase,
} from './application/homework-attachments.use-cases';
import {
  CreateHomeworkQuestionOptionUseCase,
  CreateHomeworkQuestionUseCase,
  DeleteHomeworkQuestionOptionUseCase,
  DeleteHomeworkQuestionUseCase,
  GetHomeworkQuestionUseCase,
  ListHomeworkQuestionsUseCase,
  ReorderHomeworkQuestionOptionUseCase,
  ReorderHomeworkQuestionUseCase,
  UpdateHomeworkQuestionOptionUseCase,
  UpdateHomeworkQuestionUseCase,
} from './application/homework-questions.use-cases';
import { HomeworkAttachmentsController } from './controller/homework-attachments.controller';
import { HomeworkAssignmentsController } from './controller/homework-assignments.controller';
import { HomeworkQuestionsController } from './controller/homework-questions.controller';
import { HomeworkSubmissionContentController } from './controller/homework-submission-content.controller';
import { HomeworkRepository } from './infrastructure/homework.repository';

@Module({
  imports: [AuthModule],
  controllers: [
    HomeworkAssignmentsController,
    HomeworkQuestionsController,
    HomeworkAttachmentsController,
    HomeworkSubmissionContentController,
  ],
  providers: [
    HomeworkRepository,
    ListHomeworkAssignmentsUseCase,
    GetHomeworkAssignmentUseCase,
    CreateHomeworkAssignmentUseCase,
    UpdateHomeworkAssignmentUseCase,
    PublishHomeworkAssignmentUseCase,
    CloseHomeworkAssignmentUseCase,
    CancelHomeworkAssignmentUseCase,
    ListHomeworkTargetsUseCase,
    ResolveHomeworkTargetsUseCase,
    GetHomeworkSubmissionUseCase,
    ListHomeworkSubmissionsForReviewUseCase,
    GetHomeworkSubmissionForReviewUseCase,
    ReviewHomeworkSubmissionUseCase,
    SaveHomeworkSubmissionDraftUseCase,
    SubmitHomeworkSubmissionUseCase,
    ListHomeworkSubmissionAnswersUseCase,
    GetHomeworkSubmissionAnswerUseCase,
    ListStudentHomeworkAnswersUseCase,
    SaveStudentHomeworkAnswersDraftUseCase,
    SaveStudentHomeworkAnswerUseCase,
    ListHomeworkSubmissionAttachmentsUseCase,
    ListStudentHomeworkSubmissionAttachmentsUseCase,
    CreateStudentHomeworkSubmissionAttachmentUseCase,
    UpdateStudentHomeworkSubmissionAttachmentUseCase,
    ReorderStudentHomeworkSubmissionAttachmentUseCase,
    DeleteStudentHomeworkSubmissionAttachmentUseCase,
    ListHomeworkQuestionsUseCase,
    GetHomeworkQuestionUseCase,
    CreateHomeworkQuestionUseCase,
    UpdateHomeworkQuestionUseCase,
    ReorderHomeworkQuestionUseCase,
    DeleteHomeworkQuestionUseCase,
    CreateHomeworkQuestionOptionUseCase,
    UpdateHomeworkQuestionOptionUseCase,
    ReorderHomeworkQuestionOptionUseCase,
    DeleteHomeworkQuestionOptionUseCase,
    ListHomeworkAttachmentsUseCase,
    CreateHomeworkAttachmentUseCase,
    UpdateHomeworkAttachmentUseCase,
    ReorderHomeworkAttachmentUseCase,
    DeleteHomeworkAttachmentUseCase,
  ],
  exports: [
    HomeworkRepository,
    ListHomeworkAssignmentsUseCase,
    GetHomeworkAssignmentUseCase,
    CreateHomeworkAssignmentUseCase,
    UpdateHomeworkAssignmentUseCase,
    PublishHomeworkAssignmentUseCase,
    CloseHomeworkAssignmentUseCase,
    CancelHomeworkAssignmentUseCase,
    ListHomeworkTargetsUseCase,
    ResolveHomeworkTargetsUseCase,
    GetHomeworkSubmissionUseCase,
    ListHomeworkSubmissionsForReviewUseCase,
    GetHomeworkSubmissionForReviewUseCase,
    ReviewHomeworkSubmissionUseCase,
    SaveHomeworkSubmissionDraftUseCase,
    SubmitHomeworkSubmissionUseCase,
    ListHomeworkSubmissionAnswersUseCase,
    GetHomeworkSubmissionAnswerUseCase,
    ListStudentHomeworkAnswersUseCase,
    SaveStudentHomeworkAnswersDraftUseCase,
    SaveStudentHomeworkAnswerUseCase,
    ListHomeworkSubmissionAttachmentsUseCase,
    ListStudentHomeworkSubmissionAttachmentsUseCase,
    CreateStudentHomeworkSubmissionAttachmentUseCase,
    UpdateStudentHomeworkSubmissionAttachmentUseCase,
    ReorderStudentHomeworkSubmissionAttachmentUseCase,
    DeleteStudentHomeworkSubmissionAttachmentUseCase,
    ListHomeworkQuestionsUseCase,
    GetHomeworkQuestionUseCase,
    CreateHomeworkQuestionUseCase,
    UpdateHomeworkQuestionUseCase,
    ReorderHomeworkQuestionUseCase,
    DeleteHomeworkQuestionUseCase,
    CreateHomeworkQuestionOptionUseCase,
    UpdateHomeworkQuestionOptionUseCase,
    ReorderHomeworkQuestionOptionUseCase,
    DeleteHomeworkQuestionOptionUseCase,
    ListHomeworkAttachmentsUseCase,
    CreateHomeworkAttachmentUseCase,
    UpdateHomeworkAttachmentUseCase,
    ReorderHomeworkAttachmentUseCase,
    DeleteHomeworkAttachmentUseCase,
  ],
})
export class HomeworkModule {}
